version: '2'
services:
    jhipsterbpm-app:
        image: jhipsterbpm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterbpm-postgresql:5432/jhipsterbpm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterbpm-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterbpm-postgresql
